Repository benchttp/engine, pull requests merged in 2022-10, with the labels that each got.

#45 fix: reflectpath.Resolver.ResolveValue incorrectly panics
  runner/internal/reflectpath/value.go
Labels: bug

#47 feat(tests): retrieve got value
  cmd/server/response/report.go
  runner/internal/tests/tests.go
  runner/internal/tests/tests_test.go
Labels: scope:server

#46 ci: dispatch update to benchttp/desktop
  .github/workflows/dispatch.yml
Labels: enhancement

#26 refactor: config
  cmd/server/main.go
  configparse/json.go
  configparse/json_test.go
  configparse/parse.go
  configparse/parser_json.go
  configparse/parser_json_test.go
  configparse/parser_yaml.go
  configparse/parser_yaml_test.go
  examples/config/default.yml
  examples/config/full.yml
  runner/internal/config/config.go
  runner/internal/config/config_test.go
  runner/internal/config/default.go
  runner/internal/config/field.go
  runner/internal/config/field_test.go
  runner/runner.go
Labels: must have, scope:core, scope:cli

#54 docs: write main documentation
  README.md
Labels: documentation, must have, scope:core

#55 chore: remove server app
  .github/workflows/dispatch.yml
  cmd/server/main.go
  go.mod
  go.sum
  httpclient/doc.go
  httpclient/handle.go
  httpclient/port.go
  httpclient/response/error.go
  httpclient/response/progress.go
  httpclient/response/report.go
  httpclient/response/response.go
  httpclient/serve.go
Labels: must have, scope:server
