Repository benchttp/engine, pull requests merged in 2022-09, with the labels that each got.

#38 feat: use free port
  .env.development
  cmd/server/main.go
  go.mod
  go.sum
Labels: must have, scope:server

#35 feat: compute stats from requester result
  runner/internal/metrics/aggregate.go
  runner/internal/metrics/aggregate_test.go
  runner/internal/metrics/field.go
  runner/internal/metrics/timestats/sort.go
  runner/internal/metrics/timestats/timestats.go
  runner/internal/metrics/timestats/timestats_test.go
  runner/internal/report/report.go
  runner/internal/report/report_test.go
  runner/internal/tests/predicate_test.go
  runner/internal/tests/tests_test.go
  runner/runner.go
Labels: must have, scope:core

#41 feat: allow test suites for new metrics
  internal/configparse/parse.go
  internal/configparse/parse_test.go
  internal/configparse/testdata/valid/benchttp.json
  internal/configparse/testdata/valid/benchttp.yaml
  internal/configparse/testdata/valid/benchttp.yml
  runner/internal/metrics/aggregate.go
  runner/internal/metrics/field.go
  runner/internal/metrics/field_test.go
  runner/internal/metrics/metrics.go
  runner/internal/metrics/metrics_test.go
  runner/internal/reflectpath/resolver.go
  runner/internal/reflectpath/type.go
  runner/internal/reflectpath/value.go
  runner/internal/tests/predicate_test.go
  runner/internal/tests/tests_test.go
  runner/runner.go
Labels: enhancement, must have, scope:core

#43 fix(timestats): computeMedian panics on n == 2
  runner/internal/metrics/aggregate_test.go
  runner/internal/metrics/timestats/timestats.go
  runner/internal/metrics/timestats/timestats_test.go
Labels: bug, must have

#44 fix(server): conventional camel-cased JSON responses
  cmd/server/main.go
  cmd/server/response/error.go
  cmd/server/response/progress.go
  cmd/server/response/report.go
  cmd/server/response/response.go
  runner/internal/metrics/aggregate.go
  runner/internal/recorder/progress.go
  runner/internal/recorder/recorder.go
  runner/internal/recorder/tracer.go
  runner/runner.go
Labels: must have, scope:server
